[package]
name = "avi-p2p-embedded"
version = "0.1.0"
edition = "2021"

[dependencies]
avi-p2p-protocol = { path = "../protocol" }
postcard = "1.0"
serde = { version = "1.0", default-features = false }